pipeline {
agent any

environment {
    DOCKER_IMAGE = "jesoas/finead-todo-app:latest"
}

stages {

    stage('Build Dependencies') {
        steps {
            dir('TODO/todo_backend') {
                sh 'npm install'
            }
            dir('TODO/todo_frontend') {
                sh 'npm install'
            }
        }
    }

    stage('Containerise') {
        steps {
	    dir('TODO'){
                sh 'docker build -t $DOCKER_IMAGE .'
            }
	}
    }

    stage('Push Image') {
        steps {
            withCredentials([usernamePassword(
                credentialsId: 'dockerhub-creds',
                usernameVariable: 'DOCKER_USER',
                passwordVariable: 'DOCKER_PASS'
            )]) {
                sh '''
                echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                docker push $DOCKER_IMAGE
                '''
            }
        }
    }

}

}
